# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 794b98f5fbc56dcd2a58f149e4cead85c31da16920d5f2b879c90b9c5bc196dd7d7e527116ff3a1854047b562d4d8228f12b23d21ec02e20514594068d454508

test:
  secret_key_base: 40da8dd6f9d8e76c54f676a572abbc6a2358d7052f531e00cb9bb3bf9666da84e9d50fa05551dd0335f54448429c4c8bfa1a87ef3304f06a3181aa25728cd781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
